// Generated by scripts/optimize-donetsk-images.mjs. Do not edit by hand.
export const donetskImages = {
  "vehicle": {
    "width": 767,
    "height": 656,
    "avif": [
      {
        "src": "/donetsk/images/vehicle-384-61e09b0a3d91.avif",
        "width": 384
      },
      {
        "src": "/donetsk/images/vehicle-640-8c706ebdc532.avif",
        "width": 640
      },
      {
        "src": "/donetsk/images/vehicle-767-0a86e5abb46b.avif",
        "width": 767
      }
    ],
    "webp": [
      {
        "src": "/donetsk/images/vehicle-384-cbf9d9599b08.webp",
        "width": 384
      },
      {
        "src": "/donetsk/images/vehicle-640-0af191287b63.webp",
        "width": 640
      },
      {
        "src": "/donetsk/images/vehicle-767-97b70f5c3776.webp",
        "width": 767
      }
    ]
  },
  "interior": {
    "width": 840,
    "height": 558,
    "avif": [
      {
        "src": "/donetsk/images/interior-384-acf42b241b3f.avif",
        "width": 384
      },
      {
        "src": "/donetsk/images/interior-640-085f37902d8e.avif",
        "width": 640
      },
      {
        "src": "/donetsk/images/interior-840-8f1e9516175b.avif",
        "width": 840
      }
    ],
    "webp": [
      {
        "src": "/donetsk/images/interior-384-4dc8ec4ce7a7.webp",
        "width": 384
      },
      {
        "src": "/donetsk/images/interior-640-feb9e63066a7.webp",
        "width": 640
      },
      {
        "src": "/donetsk/images/interior-840-4c257118cdda.webp",
        "width": 840
      }
    ]
  },
  "pensioner": {
    "width": 900,
    "height": 509,
    "avif": [
      {
        "src": "/donetsk/images/pensioner-384-c53f79c5f19e.avif",
        "width": 384
      },
      {
        "src": "/donetsk/images/pensioner-640-ae6c328fb10c.avif",
        "width": 640
      },
      {
        "src": "/donetsk/images/pensioner-900-9f8def031501.avif",
        "width": 900
      }
    ],
    "webp": [
      {
        "src": "/donetsk/images/pensioner-384-7367fac7fb0e.webp",
        "width": 384
      },
      {
        "src": "/donetsk/images/pensioner-640-704ce88ac8eb.webp",
        "width": 640
      },
      {
        "src": "/donetsk/images/pensioner-900-d7d9584a98b6.webp",
        "width": 900
      }
    ]
  },
  "veteran": {
    "width": 549,
    "height": 364,
    "avif": [
      {
        "src": "/donetsk/images/veteran-384-e666379c1c44.avif",
        "width": 384
      },
      {
        "src": "/donetsk/images/veteran-549-c07876f1dba7.avif",
        "width": 549
      }
    ],
    "webp": [
      {
        "src": "/donetsk/images/veteran-384-0167b4b514f4.webp",
        "width": 384
      },
      {
        "src": "/donetsk/images/veteran-549-459d3509f3d9.webp",
        "width": 549
      }
    ]
  }
} as const;
